steps:
  # Paso 1: construir y publicar la imagen en Artifact Registry con la etiqueta del build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "us-central1-docker.pkg.dev/fog-serverless/cloud-run-repo/fog-ingestion:${BUILD_ID}"
      - "-t"
      - "us-central1-docker.pkg.dev/fog-serverless/cloud-run-repo/fog-ingestion:latest"
      - "./services/ingest"

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "us-central1-docker.pkg.dev/fog-serverless/cloud-run-repo/fog-ingestion:${BUILD_ID}"

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "us-central1-docker.pkg.dev/fog-serverless/cloud-run-repo/fog-ingestion:latest"

  # Paso 2: actualizar configuración de Pulumi para apuntar a la imagen recién construida
  - name: pulumi/pulumi
    entrypoint: pulumi
    args:
      - config
      - set
      - imageTag
      - "${BUILD_ID}"
      - "--cwd"
      - "infra"
    env:
      - "PULUMI_CONFIG_PASSPHRASE="

  # Paso 3: aplicar infraestructura con Pulumi (única fuente de verdad)
  - name: pulumi/pulumi
    entrypoint: pulumi
    args: ["up", "--yes", "--cwd", "infra"]
    env:
      - "PULUMI_CONFIG_PASSPHRASE="

options:
  logging: CLOUD_LOGGING_ONLY
