steps:
  # Paso 1: build de la imagen de ingesta
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/${_PROJECT}/cloud-run-repo/fog-ingestion:${_TAG}"
      - "./services/ingest"

  # Paso 2: push a Artifact Registry
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/${_PROJECT}/cloud-run-repo/fog-ingestion:${_TAG}"

  # Paso 3: deploy Cloud Run (solo ingesta HTTP)
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-ingest
    entrypoint: sh
    args:
      - "-c"
      - |
        set -e
        gcloud run deploy fog-ingestion \
          --project "${_PROJECT}" \
          --region "${_REGION}" \
          --image "${_REGION}-docker.pkg.dev/${_PROJECT}/cloud-run-repo/fog-ingestion:${_TAG}" \
          --platform managed \
          --allow-unauthenticated \
          --set-env-vars "PROJECT_ID=${_PROJECT},TOPIC_NAME=fog-events,INGEST_API_KEY=${_INGEST_API_KEY}"

  # Paso 4: deploy Cloud Function Gen2 (procesador Pub/Sub)
  - name: gcr.io/cloud-builders/gcloud
    id: deploy-processor
    entrypoint: sh
    args:
      - "-c"
      - |
        set -e
        gcloud functions deploy fog-processor \
          --gen2 \
          --region="${_REGION}" \
          --project="${_PROJECT}" \
          --runtime=python311 \
          --entry-point=process_event \
          --trigger-topic=fog-events \
          --source=functions/processor

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _PROJECT: fog-serverless
  _REGION: us-central1
  _TAG: latest
  _INGEST_API_KEY: "fog-secret-123"
